# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i_was_here', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='was_here',
            name='date_of_visit',
        ),
    ]
